version: "3.0"

services:
  greeter:
    build:
      context: .
    image: gds-service-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    external_links:
      - nats:nats
    network_mode: bridge
